/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Museum.gltf 
*/
"use client"

import React, { useRef } from 'react'
import { useGLTF , useTexture , useVideoTexture} from '@react-three/drei';
import * as THREE from 'three';

export function Museum1(props) {
  const texture=useTexture('models/Museumtexture.png');
  texture.flipY=false;
  texture.colorSpace=THREE.SRGBColorSpace;
  const textureMaterial=new THREE.MeshStandardMaterial({
    map:texture,
  })
  const { nodes, materials } = useGLTF('models/Museum.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Corridoor.geometry} material={textureMaterial} position={[0, 2.061, 69.472]} />
      <mesh geometry={nodes.Celings.geometry} material={textureMaterial} position={[0, 2.081, 34.518]} />
      <mesh geometry={nodes.Entrance.geometry} material={textureMaterial} position={[0, 2.061, 0]} />
      <mesh geometry={nodes.Ground.geometry} material={textureMaterial} position={[0, 2.061, 51.853]} />
      <mesh geometry={nodes.Khidki.geometry} material={textureMaterial} position={[0, 2.061, 69.472]} />
      <mesh geometry={nodes.Easels.geometry} material={textureMaterial} position={[0.128, 1.129, 40.618]} rotation={[-1.453, 0.066, 0.506]} />
      <mesh geometry={nodes['2'].geometry} material={textureMaterial} position={[4.957, 2.755, -10.135]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['1'].geometry} material={textureMaterial} position={[4.957, 2.755, -1.343]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['3'].geometry} material={textureMaterial} position={[-4.962, 2.755, -10.135]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['4'].geometry} material={textureMaterial} position={[-4.962, 2.755, -1.343]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['2001'].geometry} material={textureMaterial} position={[4.957, 2.755, 6.89]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['1001'].geometry} material={textureMaterial} position={[4.957, 2.755, 15.682]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['3001'].geometry} material={textureMaterial} position={[-4.962, 2.755, 6.89]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['4001'].geometry} material={textureMaterial} position={[-4.962, 2.755, 15.682]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['2002'].geometry} material={textureMaterial} position={[4.957, 2.755, 24.755]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['1002'].geometry} material={textureMaterial} position={[4.957, 2.755, 33.547]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['3002'].geometry} material={textureMaterial} position={[-4.962, 2.755, 24.755]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['4002'].geometry} material={textureMaterial} position={[-4.962, 2.755, 33.547]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['2003'].geometry} material={textureMaterial} position={[4.957, 2.755, 41.78]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['1003'].geometry} material={textureMaterial} position={[4.957, 2.755, 50.572]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['3003'].geometry} material={textureMaterial} position={[-4.962, 2.755, 41.78]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['4003'].geometry} material={textureMaterial} position={[-4.962, 2.755, 50.572]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['2004'].geometry} material={textureMaterial} position={[4.957, 2.755, 59.532]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['1004'].geometry} material={textureMaterial} position={[4.957, 2.755, 68.324]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['3004'].geometry} material={textureMaterial} position={[-4.962, 2.755, 59.532]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['4004'].geometry} material={textureMaterial} position={[-4.962, 2.755, 68.324]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['2005'].geometry} material={textureMaterial} position={[4.957, 2.755, 76.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['1005'].geometry} material={textureMaterial} position={[4.957, 2.755, 85.349]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['3005'].geometry} material={textureMaterial} position={[-4.962, 2.755, 76.557]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['4005'].geometry} material={textureMaterial} position={[-4.962, 2.755, 85.349]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Plane036.geometry} material={textureMaterial} position={[-1.735, 0.081, -2.886]} rotation={[-1.442, -0.042, -0.313]} />
      <mesh geometry={nodes.Plane037.geometry} material={textureMaterial} position={[1.921, 0.081, -3.037]} rotation={[-1.453, 0.066, 0.506]} />
      <mesh geometry={nodes.Plane038.geometry} material={textureMaterial} position={[-1.735, 0.081, 15.553]} rotation={[-1.442, -0.042, -0.313]} />
      <mesh geometry={nodes.Plane039.geometry} material={textureMaterial} position={[1.921, 0.081, 15.403]} rotation={[-1.453, 0.066, 0.506]} />
      <mesh geometry={nodes.Plane040.geometry} material={textureMaterial} position={[-1.735, 0.081, 31.017]} rotation={[-1.442, -0.042, -0.313]} />
      <mesh geometry={nodes.Plane041.geometry} material={textureMaterial} position={[1.921, 0.081, 30.867]} rotation={[-1.453, 0.066, 0.506]} />
      <mesh geometry={nodes.Plane042.geometry} material={textureMaterial} position={[-1.735, 0.081, 49.456]} rotation={[-1.442, -0.042, -0.313]} />
      <mesh geometry={nodes.Plane043.geometry} material={textureMaterial} position={[1.921, 0.081, 49.306]} rotation={[-1.453, 0.066, 0.506]} />
      <mesh geometry={nodes.Plane044.geometry} material={textureMaterial} position={[-1.735, 0.081, 65.117]} rotation={[-1.442, -0.042, -0.313]} />
      <mesh geometry={nodes.Plane045.geometry} material={textureMaterial} position={[1.921, 0.081, 64.967]} rotation={[-1.453, 0.066, 0.506]} />
      <mesh geometry={nodes.Plane046.geometry} material={textureMaterial} position={[-1.735, 0.081, 83.557]} rotation={[-1.442, -0.042, -0.313]} />
      <mesh geometry={nodes.Plane047.geometry} material={textureMaterial} position={[1.921, 0.081, 83.406]} rotation={[-1.453, 0.066, 0.506]} />
    </group>
  )
}

useGLTF.preload('models/Museum.gltf')
